name: Build and Publish IOS

on:
  push:
    tags:
      - v**
  workflow_dispatch:

env:
  SIGN: false

jobs:
  build-and-publish-jvm-android:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable again
        run: chmod +x ./gradlew

      - name: Publish to Sonatype repository
        run: |
          ./gradlew clean publishToMavenLocal
          ls -ln ./build/libs && echo 'Complete'
        #run: ./gradlew clean publishAllPublicationsToSonatypeRepository

  build-and-release-ios:
    runs-on: macos-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable again
        run: chmod +x ./gradlew

      - name: Build XCFramework
        run: ./gradlew clean podPublishXCFramework

      - name: Checkout ios sources
        uses: actions/checkout@v3
        with:
          path: biometric-sdk-ios-release
          repository: biometric-technologies/biometric-sdk-ios-release
          ref: master

      - name: Update ios sources
        working-directory: ./biometric-sdk-ios-release
        run: cp -a ./../build/cocoapods/publish/debug/. .

      - name: Get project version
        run: echo "VERSION=$(grep 'version =' build.gradle.kts | awk '{print $3}' | sed 's/\"//g')" >> $GITHUB_ENV

      - name: Commit and push ios sources
        working-directory: ./biometric-sdk-ios-release
        run: |
          mkdir -p ~/.ssh 
          touch ~/.ssh/deploy_key
          echo "${{ secrets.GIT_DEPLOY_KEY }}" >> ~/.ssh/deploy_key
          touch ~/.ssh/config
          echo "Host github-release-repo\n HostName github.com\n IdentityFile ~/.ssh/deploy_key" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git commit -a -m "Release $VERSION"
          git push
          git tag v$VERSION
          git push --tags

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Release library
        working-directory: ./biometric-sdk-ios-release
        #run: pod trunk push BiometricSdk.podspec
        run: ls -ln && echo 'Complete'
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}